import type { FinanceDb } from "@/features/finance/types"

export function buildDefaultDb(now = new Date()): FinanceDb {
  const y = now.getFullYear()
  const mo = String(now.getMonth() + 1).padStart(2, "0")
  const d = (n: number) =>
    `${y}-${mo}-${String(Math.max(1, n)).padStart(2, "0")}` as const
  const t = now.getDate()

  return {
    accounts: [
      {
        id: 1,
        num: 1,
        name: "Monobank",
        type: "card",
        currency: "UAH",
        initialBalance: 18500,
      },
      {
        id: 2,
        num: 2,
        name: "ПриватБанк",
        type: "card",
        currency: "UAH",
        initialBalance: 6200,
      },
      {
        id: 3,
        num: 3,
        name: "Готівка",
        type: "cash",
        currency: "UAH",
        initialBalance: 1800,
      },
    ],
    categories: [
      { id: 1, num: 1, name: "Супермаркет", parent: "Їжа", budget: 3000 },
      { id: 2, num: 2, name: "Кафе/Ресторани", parent: "Їжа", budget: 1500 },
      { id: 3, num: 3, name: "Пальне", parent: "Транспорт", budget: 2000 },
      { id: 4, num: 4, name: "Таксі", parent: "Транспорт", budget: 500 },
      { id: 5, num: 5, name: "Електрика", parent: "Комунальні", budget: 800 },
      { id: 6, num: 6, name: "Інтернет", parent: "Комунальні", budget: 300 },
      { id: 7, num: 7, name: "Аптека", parent: "Здоров'я", budget: 600 },
      { id: 8, num: 8, name: "Підписки", parent: "Розваги", budget: 400 },
      { id: 9, num: 9, name: "Одяг та взуття", parent: "Шопінг", budget: 1500 },
    ],
    transactions: [
      {
        id: 1,
        num: 1,
        date: d(1),
        name: "Зарплата",
        amount: 42000,
        type: "income",
        accountId: 1,
        categoryId: null,
        note: "",
        transferId: null,
      },
      {
        id: 2,
        num: 2,
        date: d(10),
        name: "Фріланс",
        amount: 9500,
        type: "income",
        accountId: 1,
        categoryId: null,
        note: "Проєкт",
        transferId: null,
      },
      {
        id: 3,
        num: 3,
        date: d(t),
        name: "Сільпо",
        amount: 387,
        type: "expense",
        accountId: 1,
        categoryId: 1,
        note: "",
        transferId: null,
      },
      {
        id: 4,
        num: 4,
        date: d(t),
        name: "Кава",
        amount: 92,
        type: "expense",
        accountId: 1,
        categoryId: 2,
        note: "Рандеву",
        transferId: null,
      },
      {
        id: 5,
        num: 5,
        date: d(t - 1),
        name: "АТБ",
        amount: 276,
        type: "expense",
        accountId: 3,
        categoryId: 1,
        note: "",
        transferId: null,
      },
      {
        id: 6,
        num: 6,
        date: d(t - 1),
        name: "Bolt",
        amount: 138,
        type: "expense",
        accountId: 1,
        categoryId: 4,
        note: "",
        transferId: null,
      },
      {
        id: 7,
        num: 7,
        date: d(t - 2),
        name: "Електрика",
        amount: 680,
        type: "expense",
        accountId: 2,
        categoryId: 5,
        note: "Листопад",
        transferId: null,
      },
      {
        id: 8,
        num: 8,
        date: d(t - 2),
        name: "Netflix",
        amount: 179,
        type: "expense",
        accountId: 1,
        categoryId: 8,
        note: "",
        transferId: null,
      },
    ],
    nid: { accounts: 4, categories: 10, transactions: 9 },
  }
}

